name: Deploy

on: 
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Flask app
        uses: appleboy/ssh-action@v0.1.2
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}

          scripts: |
          cd var/www/
          mkdir py-project
          cd py-project
          git clone git@github.com/Jsloot1986/Jochum_sloot-CD.git
          echo 'Deployment succesful to digital ocean'